twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic   : cmd_vel_teleop
        timeout : 0.5
        priority: 10
      joystick: 
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      emergency: 
        topic   : cmd_vel_emerg
        timeout : 0.5
        priority: 100